# Generated by Django 2.1.5 on 2019-03-14 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0033_remove_fight_operator'),
        ('tournament', '0060_tournament_possiblejuror_reapply'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_time', models.DateTimeField(auto_now_add=True)),
                ('elapsed', models.IntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Phase')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Stage')),
            ],
        ),
    ]
