# Generated by Django 2.1.9 on 2019-07-05 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190407_1403'),
        ('printer', '0027_auto_20190408_1159'),
        ('tournament', '0062_tournament_publish_juror_availability'),
        ('fight', '0003_auto_20190316_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('error_pages', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Attendee')),
                ('pdf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.Pdf')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
    ]
