# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0046_auto_20180320_1323'),
        ('account', '0020_participationrole_attending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('registration', 'Registration')], max_length=25, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailtemplates', to='tournament.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(blank=True, max_length=1000)),
                ('src', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailtemplateversions', to='account.ActiveUser')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.Template')),
            ],
        ),
    ]
