# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-21 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0047_tournament_logo'),
        ('postoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('name', 'tournament')]),
        ),
    ]
