# Generated by Django 2.1.2 on 2018-11-11 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0054_auto_20181007_2300'),
        ('postoffice', '0003_auto_20181111_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('registration', 'Registration'), ('jurorfeedback', 'Juror Feedback')], max_length=25)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postoffice.Template')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_mail_template', to='tournament.Tournament')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='defaulttemplate',
            unique_together={('tournament', 'type')},
        ),
    ]
