"""
Django settings for cc project.

Generated by 'django-admin startproject' using Django 1.10.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
#sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, BASE_DIR)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if "SECRET_KEY" in os.environ:
    SECRET_KEY = os.environ['SECRET_KEY']
else:
    try:
        from .secret_key import *
    except:
        SECRET_KEY = 'xa-oc@z1d$+o*g_w@h9@ef^zri)i)^c5*8+$za4&*x1g@7bh3a'

# SECURITY WARNING: don't run with debug turned on in production!

DEV = False

ALLOWED_HOSTS = ["iypt.nlogn.org","dev.iypt.nlogn.org","cc.iypt.org","cc.iypt.net"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cc',
    'ordered_model',
    'apps.tournament.apps.TournamentConfig',
    'apps.account.apps.AccountConfig',
    'apps.plan.apps.PlanConfig',
    'apps.jury.apps.JuryConfig',
    'apps.team.apps.TeamConfig',
    'apps.bank.apps.BankConfig',
    'apps.result.apps.ResultConfig',
    'apps.fight.apps.FightConfig',
    'apps.schedule.apps.ScheduleConfig',
    'apps.printer.apps.PrinterConfig',
    'apps.postoffice.apps.PostofficeConfig',
    'apps.management.apps.ManagementConfig',
    'apps.about.apps.AboutConfig',
    'apps.registration.apps.RegistrationConfig',
    'codemirror2',
    'channels',
    'bootstrap3',
    'apps.dashboard.apps.DashboardConfig',
    'django_select2',
    'dbbackup',
    'tellme',
    'formtools',
    'hijack',
    'django_celery_results',
    'raven.contrib.django.raven_compat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.tournament.middleware.AppPermissionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cc.wsgi.application'

ASGI_APPLICATION = "cc.routing.application"



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'glue-media')

DBBACKUP_STORAGE = 'django.core.files.storage.FileSystemStorage'
DBBACKUP_STORAGE_OPTIONS = {'location': os.path.join(os.path.dirname(BASE_DIR), 'dbbackup')}

SELECT2_CSS = '/static/select2/dist/css/select2.css'
SELECT2_JS = '/static/select2/dist/js/select2.min.js'
