from django.urls import path, re_path

from .views import (
    FightJuryView,
    FightPreView,
    FightScanView,
    FightView,
    ListScanProessing,
    ManageFightsView,
    PdfPreviewView,
    PdfRankingView,
    PdfResultView,
    PublishView,
    ScanView,
    SlidesImport,
    SlidesView,
    clocks,
    fight_phases,
    fightclock,
    fightreplicaclock,
    genpdfpreview,
    genpdfrank,
    genpdfresult,
    get_pdf_page,
    plan,
    processPDF,
    validate_plan,
)

app_name = "fight"

urlpatterns = [
    # url(r'^', include('django.contrib.auth.urls')),
    path("plan/", plan, name="plan"),
    path("validate/", validate_plan, name="validate"),
    path("publish/", PublishView.as_view(), name="publish"),
    path("manage/", ManageFightsView.as_view(), name="manage"),
    path("fight/<int:fight_id>/", FightJuryView.as_view(), name="fightjury"),
    re_path(
        r"^fight/(?P<fight_id>[0-9]+)/preview.pdf$",
        PdfPreviewView.as_view(),
        name="pdfpreview",
    ),
    re_path(
        r"^fight/(?P<fight_id>[0-9]+)/result.pdf$",
        PdfResultView.as_view(),
        name="pdfresult",
    ),
    path("fight/<int:fight_id>/genpreview/", genpdfpreview, name="genpdfpreview"),
    path("fight/<int:fight_id>/genresult/", genpdfresult, name="genpdfresult"),
    path("round/<int:round_nr>/genrank/", genpdfrank, name="genpdfrank"),
    re_path(
        r"^round/(?P<round_nr>[0-9]+)/ranking.pdf$",
        PdfRankingView.as_view(),
        name="pdfrank",
    ),
    path("round/<int:round_nr>/clocks/", clocks, name="clocks"),
    path("round/<int:round_nr>/timing/", fight_phases, name="timing"),
    path("fight/<int:fight_id>/check/", FightPreView.as_view(), name="fightpre"),
    path("fight/<int:fight_id>/scans/", FightScanView.as_view(), name="fightscan"),
    re_path(
        r"^scans/(?P<stage_id>[0-9]+)/(?P<typ>[a-z]+).jpg$",
        ScanView.as_view(),
        name="scanimage",
    ),
    re_path(
        r"^fight/(?P<fight_id>[0-9]+)/(?P<stage>[1-9])/clock/$",
        fightclock,
        name="fightclock",
    ),
    re_path(
        r"^fight/(?P<fight_id>[0-9]+)/(?P<stage>[1-9])/replicaclock/$",
        fightreplicaclock,
        name="fightreplicaclock",
    ),
    re_path(
        r"^fight/(?P<fight_id>[0-9]+)/(?P<stage>[1-9])/$",
        FightView.as_view(),
        name="fight",
    ),
    path("processing/", ListScanProessing.as_view(), name="processing"),
    path("slides/", SlidesView.as_view(), name="slides"),
    path(
        "slides/import/server/<int:id>/round/<int:round_order>/<path:path>",
        SlidesImport.as_view(),
        name="slides_import",
    ),
    path(
        "processing/pdf/<int:pdf_id>/page/<int:page>",
        ListScanProessing.as_view(),
        name="processing",
    ),
    path("get_page/pdf/<int:pdf_id>/page/<int:page>", get_pdf_page, name="get_page"),
    path("processing/new", processPDF, name="process_new"),
]
