# Generated by Django 3.1.6 on 2021-02-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0069_tournament_bank_default_contingency_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('api_url', models.URLField(max_length=256, verbose_name='API URL')),
                ('secret', models.CharField(max_length=64, verbose_name='Secret')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
