# Generated by Django 3.1.6 on 2021-02-24 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0070_auto_20210219_2217'),
        ('account', '0026_auto_20210220_2117'),
        ('virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('mute_on_start', models.BooleanField(default=False, verbose_name='mute on join')),
                ('lock_settings_disable_cam', models.BooleanField(default=False, verbose_name='disable video sharing')),
                ('lock_settings_disable_private_chat', models.BooleanField(default=False, verbose_name='disable private chat')),
                ('lock_settings_disable_note', models.BooleanField(default=False, verbose_name='disable notes')),
                ('allow_attendees_to_start_meeting', models.BooleanField(default=False, verbose_name='attendees can start meeting')),
                ('guest_policy', models.CharField(choices=[('ALWAYS_ACCEPT', 'allow guests'), ('ALWAYS_DENY', 'deny guests'), ('ASK_MODERATOR', 'ask moderator to allow guests')], default='ALWAYS_DENY', max_length=16, verbose_name='guests')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='virtual.bbbinstance')),
            ],
        ),
        migrations.CreateModel(
            name='HallRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('guest', 'Guest'), ('attendee', 'Participant'), ('moderator', 'Moderator')], max_length=40)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual.hall')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.participationrole')),
            ],
        ),
        migrations.AddField(
            model_name='hall',
            name='roles',
            field=models.ManyToManyField(blank=True, through='virtual.HallRole', to='account.ParticipationRole'),
        ),
        migrations.AddField(
            model_name='hall',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
