# Generated by Django 3.1.6 on 2021-02-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0003_auto_20210224_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='hall',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
