# Generated by Django 3.1.6 on 2021-04-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210327_1042'),
        ('virtual', '0006_stream_streamedgeserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='access',
            field=models.ManyToManyField(blank=True, to='account.ParticipationRole'),
        ),
    ]
