# Generated by Django 3.2.1 on 2021-07-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210327_1042'),
        ('virtual', '0007_stream_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='virtual_attendees',
            field=models.ManyToManyField(blank=True, to='account.Attendee'),
        ),
    ]
