# Generated by Django 3.2.1 on 2021-07-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0008_hall_virtual_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('userid', models.CharField(max_length=100)),
            ],
        ),
    ]
