# Generated by Django 3.2.1 on 2021-07-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0009_bbbguest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='virtual_guests',
            field=models.ManyToManyField(blank=True, to='virtual.BBBGuest'),
        ),
    ]
