# Generated by Django 3.2.14 on 2022-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0010_hall_virtual_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='record',
            field=models.BooleanField(default=False),
        ),
    ]
