# Generated by Django 4.2.1 on 2023-08-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0011_hall_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='external_link',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
