# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juror',
            old_name='user',
            new_name='attendee',
        ),
    ]
