# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0003_auto_20161104_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurorsession',
            name='grades',
            field=models.ManyToManyField(blank=True, through='jury.JurorGrade', to='plan.StageAttendance'),
        ),
    ]
