# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0004_auto_20161104_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorsession',
            options={'permissions': (('change_all_jurysessions', 'Can change jury any time'),)},
        ),
    ]
