# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0006_auto_20161106_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juror',
            options={'ordering': ['attendee__active_user__user__last_name'], 'permissions': (('view_juror', 'Can list all jurors and jury plans'),)},
        ),
    ]
