# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0007_auto_20161107_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorsession',
            options={'ordering': ['role', 'juror'], 'permissions': (('change_all_jurorsessions', 'Can change jury any time'),)},
        ),
    ]
