# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0008_auto_20161107_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorrole',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='jurorsession',
            options={'ordering': ['role__type', 'juror'], 'permissions': (('change_all_jurorsessions', 'Can change jury any time'),)},
        ),
        migrations.AddField(
            model_name='jurorrole',
            name='type',
            field=models.CharField(blank=True, choices=[('0ch', 'Chair'), ('1ju', 'Juror')], max_length=3, null=True),
        ),
    ]
