# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20161125_1204'),
        ('jury', '0009_auto_20161107_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='juror',
            name='conflicting',
            field=models.ManyToManyField(blank=True, to='tournament.Origin'),
        ),
    ]
