# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0012_assignresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignresult',
            name='task',
        ),
        migrations.AddField(
            model_name='assignresult',
            name='task_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
