# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0014_auto_20170107_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorgrade',
            options={'permissions': (('view_results', 'View published results'), ('validate_grades', 'Validate grades after manual check'))},
        ),
        migrations.AlterModelOptions(
            name='jurorsession',
            options={'ordering': ['role__type', 'juror'], 'permissions': (('change_all_jurorsessions', 'Can change jury any time'), ('assign_jurors', 'Can assign jurors to fights'), ('delete_all_jurorsessions', 'Delete all juror sessions together'))},
        ),
    ]
