# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0019_auto_20170704_0434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juror',
            options={'ordering': ['attendee__active_user__user__last_name'], 'permissions': (('view_juror', 'Can list all jurors and jury plans'), ('clock', 'Can view clock'), ('publish_fights', 'Can publish fights and previews'))},
        ),
    ]
