# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 04:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0020_auto_20170704_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorsession',
            options={'ordering': ['role__type', 'juror'], 'permissions': (('change_all_jurorsessions', 'Can change jury any time'), ('assign_jurors', 'Can assign jurors to fights'), ('delete_all_jurorsessions', 'Delete all juror sessions together'))},
        ),
    ]
