# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0022_auto_20180115_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
