# Generated by Django 2.0.3 on 2018-06-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0025_auto_20180226_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juror',
            options={'ordering': ['attendee__active_user__user__last_name'], 'permissions': (('view_juror', 'Can list all jurors and jury plans'), ('clock', 'Can view clock'), ('clocks', 'Can view all clocks'), ('publish_fights', 'Can publish fights and previews'))},
        ),
    ]
