# Generated by Django 2.0.3 on 2018-08-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0028_assignresult_fix_rounds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jurorgrade',
            options={'permissions': (('view_results', 'View published results'), ('validate_grades', 'Validate grades after manual check'), ('grade_dump', 'Dump grades and results'))},
        ),
    ]
