# Generated by Django 2.1 on 2018-08-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0029_auto_20180802_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juror',
            options={'ordering': ['attendee__active_user__user__last_name'], 'permissions': (('clock', 'Can view clock'), ('clocks', 'Can view all clocks'), ('publish_fights', 'Can publish fights and previews'))},
        ),
    ]
