# Generated by Django 2.1.2 on 2018-11-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0030_auto_20180802_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juror',
            options={'ordering': ['attendee__active_user__user__last_name'], 'permissions': (('clock', 'Can view clock'), ('clocks', 'Can view all clocks'), ('publish_fights', 'Can publish fights and previews'), ('stats', 'Can view statistics of jurors'))},
        ),
    ]
