# Generated by Django 2.1.8 on 2019-04-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0034_stage_pdf_grading_sheets'),
        ('jury', '0033_auto_20190218_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(upload_to='')),
                ('rep', models.ImageField(upload_to='')),
                ('opp', models.ImageField(upload_to='')),
                ('rev', models.ImageField(upload_to='')),
                ('jurorsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jury.JurorSession')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Stage')),
            ],
        ),
    ]
