# Generated by Django 2.1.9 on 2019-07-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0034_gradingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='full',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='opp',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='rep',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='rev',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
