# Generated by Django 2.1.9 on 2019-07-06 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0004_scanprocessing'),
        ('jury', '0035_auto_20190705_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsheet',
            name='process_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fight.ScanProcessing'),
        ),
    ]
