# Generated by Django 2.1.9 on 2019-07-07 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0036_gradingsheet_process_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='juror',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
