# Generated by Django 3.1.6 on 2021-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0037_juror_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juror',
            name='local',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juror',
            name='possible_chair',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
