# Generated by Django 3.2.1 on 2021-05-05 10:52

import apps.jury.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jury', '0038_auto_20210206_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsheet',
            name='full',
            field=models.ImageField(blank=True, null=True, upload_to=apps.jury.models.dir_path_full),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to=apps.jury.models.dir_path_header),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='opp',
            field=models.ImageField(blank=True, null=True, upload_to=apps.jury.models.dir_path_opp),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='rep',
            field=models.ImageField(blank=True, null=True, upload_to=apps.jury.models.dir_path_rep),
        ),
        migrations.AlterField(
            model_name='gradingsheet',
            name='rev',
            field=models.ImageField(blank=True, null=True, upload_to=apps.jury.models.dir_path_rev),
        ),
    ]
