# Generated by Django 3.2.6 on 2022-02-07 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0083_tournament_jury_chair_maximum_meet_origin'),
        ('jury', '0039_auto_20210505_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='juror',
            name='max_assign',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juror',
            name='max_chair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='JurorAvailabilityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='juror',
            name='availability_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jury.juroravailabilitygroup'),
        ),
    ]
