# Generated by Django 4.2.1 on 2023-06-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210327_1042'),
        ('tournament', '0083_tournament_jury_chair_maximum_meet_origin'),
        ('jury', '0041_auto_20220527_1150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='possiblejuror',
            unique_together={('person', 'tournament')},
        ),
    ]
