# Generated by Django 4.2.1 on 2023-07-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0050_fight_virtual_record'),
        ('jury', '0042_alter_possiblejuror_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupgrade',
            name='stage_attendee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plan.stageattendance'),
            preserve_default=False,
        ),
    ]
