# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('number', 'tournament')]),
        ),
    ]
