# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20161009_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
