# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='short',
            field=models.CharField(max_length=50),
        ),
    ]
