# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_room_slug'),
        ('tournament', '0004_auto_20161105_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='final_fight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.Fight'),
        ),
    ]
