# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_team_origin'),
        ('tournament', '0006_remove_tournament_final_fight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
