# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20161209_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='teams_nr',
        ),
        migrations.RemoveField(
            model_name='templatefight',
            name='name',
        ),
        migrations.AlterField(
            model_name='templatefight',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fights', to='tournament.TemplateRound'),
        ),
        migrations.AddField(
            model_name='templateroom',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.ScheduleTemplate'),
        ),
        migrations.AddField(
            model_name='templatefight',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.TemplateRoom'),
            preserve_default=False,
        ),
    ]
