# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_origin_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('app_tournament', 'Access to Tournament app'), ('app_team', 'Access to Tournament app'), ('app_plan', 'Access to Tournament app'), ('app_jury', 'Access to Tournament app'), ('app_fight', 'Access to Tournament app'))},
        ),
    ]
