# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_auto_20161221_0318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('app_team', 'Access to Team app'), ('app_tournament', 'Access to Tournament app'), ('app_plan', 'Access to Plan app'), ('app_jury', 'Access to Jury app'), ('app_fight', 'Access to Fight app'))},
        ),
    ]
