# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_auto_20161221_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allowed_rejections',
            field=models.IntegerField(default=3),
        ),
    ]
