# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_tournament_allowed_rejections'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletemplate',
            name='teams',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
