# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_scheduletemplate_teams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('app_team', 'Access to Team app'), ('app_tournament', 'Access to Tournament app'), ('app_plan', 'Access to Plan app'), ('app_jury', 'Access to Jury app'), ('app_fight', 'Access to Fight app'), ('app_schedule', 'Access to Schedule app'))},
        ),
    ]
