# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_auto_20170105_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='results_access',
            field=models.CharField(choices=[('pub', 'public'), ('pw', 'password'), ('perm', 'permission'), ('none', 'none')], default='none', max_length=4),
        ),
        migrations.AddField(
            model_name='tournament',
            name='results_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
