# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0011_auto_20170309_1001'),
        ('tournament', '0018_auto_20170112_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_preview_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_tournament', to='printer.Template'),
        ),
    ]
