# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_tournament_default_result_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='alpha2iso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
