# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0014_auto_20170423_1354'),
        ('tournament', '0021_origin_alpha2iso'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_round_juryplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juryround_tournament', to='printer.Template'),
        ),
    ]
