# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0018_auto_20170705_1708'),
        ('tournament', '0026_auto_20170704_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_juryfeedback_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juryfeedback_tournament', to='printer.Template'),
        ),
    ]
