# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-07 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_tournament_default_round_problemselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_close',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_open',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
