# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0020_defaulttemplate'),
        ('tournament', '0028_tournament_default_round_problemselect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='default_templates',
            field=models.ManyToManyField(related_name='default_templates', through='printer.DefaultTemplate', to='printer.Template'),
        ),
    ]
