# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_auto_20170907_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='from_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='origin',
            name='short',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
