# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_auto_20170909_2138'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='origin',
            unique_together=set([('name', 'tournament')]),
        ),
    ]
