# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_tournament_default_templates'),
        ('tournament', '0031_auto_20170909_2203'),
    ]

    operations = [
    ]
