# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_merge_20180109_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='default_juryfeedback_template',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_preview_template',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_result_template',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_round_juryplan',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_round_problemselect',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_round_ranking',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='default_round_teamplan',
        ),
    ]
