# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_auto_20180109_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
