# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_tournament_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
