# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_participationrole_groups'),
        ('tournament', '0035_auto_20180115_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_notifications',
            field=models.ManyToManyField(related_name='registration_notifications', to='account.Attendee'),
        ),
    ]
