# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0036_tournament_registration_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_notifications',
            field=models.ManyToManyField(blank=True, related_name='registration_notifications', to='account.Attendee'),
        ),
    ]
