# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-12 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0040_auto_20180209_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_apply_newteam',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_apply_team',
            field=models.BooleanField(default=True),
        ),
    ]
