# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0042_auto_20180212_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fee_team',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
