# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0044_auto_20180219_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='origin',
            unique_together=set([('slug', 'tournament')]),
        ),
    ]
