# Generated by Django 2.0.3 on 2018-04-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_payment_ref_attendee'),
        ('tournament', '0048_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bank_default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Account'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bank_default_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
