# Generated by Django 2.0.3 on 2018-07-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0049_auto_20180430_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_assignmentbalance',
            field=models.FloatField(default=1.0, verbose_name='Weight of number of jury assignments'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_expassignmentbalance',
            field=models.FloatField(default=1.0, verbose_name='Weight of balance of experienced jurors'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_jurysamecountry',
            field=models.FloatField(default=1.0, verbose_name='Weight of multiple jurors from same country'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_teamandchairmeettwice',
            field=models.FloatField(default=1.0, verbose_name='Weight of team and chair meet twice'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_teamandjurormeetmultiple',
            field=models.FloatField(default=1.0, verbose_name='Weight of team and juror meet multiple'),
        ),
    ]
