# Generated by Django 2.0.3 on 2018-07-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0050_auto_20180713_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='flag_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
