# Generated by Django 2.0.3 on 2018-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0051_origin_flag_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='draw_wide',
            field=models.BooleanField(default=False),
        ),
    ]
