# Generated by Django 2.0.3 on 2018-07-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0052_tournament_draw_wide'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='jury_opt_weight_bias',
            field=models.FloatField(default=1.0, verbose_name='Weight of bias'),
        ),
    ]
