# Generated by Django 2.1.2 on 2019-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_auto_20180314_1814'),
        ('tournament', '0054_auto_20181007_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='feedback_permitted_roles',
            field=models.ManyToManyField(blank=True, related_name='feedback_permitted', to='team.TeamRole'),
        ),
    ]
