# Generated by Django 2.1.5 on 2019-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0056_origin_possible_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
