# Generated by Django 2.1.5 on 2019-02-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0058_auto_20190218_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
