# Generated by Django 2.1.5 on 2019-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0059_auto_20190219_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='possiblejuror_reapply',
            field=models.BooleanField(default=False),
        ),
    ]
