# Generated by Django 2.1.5 on 2019-03-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0060_tournament_possiblejuror_reapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='bank_expected_fee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bank_generate_invoice',
            field=models.BooleanField(default=True),
        ),
    ]
