# Generated by Django 2.2.6 on 2019-10-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0062_tournament_publish_juror_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='publish_juror_conflicting',
            field=models.BooleanField(default=False),
        ),
    ]
