# Generated by Django 2.2.6 on 2019-11-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0063_tournament_publish_juror_conflicting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': (('app_team', 'Access to Team app'), ('app_tournament', 'Access to Tournament app'), ('app_plan', 'Access to Plan app'), ('app_jury', 'Access to Jury app'), ('app_feedback', 'Access to Feedback app'), ('app_fight', 'Access to Fight app'), ('app_printer', 'Access to Printer app'), ('app_schedule', 'Access to Schedule app'), ('app_management', 'Access to Management app'), ('app_bank', 'Access to Bank app'), ('app_postoffice', 'Access to Postoffice app'), ('app_fake', 'Access to Fake app'), ('change_attendee_data', 'Customise Participation Data'), ('delete_attendee_data', 'Delete Participation Data'))},
        ),
    ]
