# Generated by Django 2.2.6 on 2019-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0064_auto_20191105_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='aypt_limited_problems',
            field=models.BooleanField(default=False),
        ),
    ]
