# Generated by Django 2.2.6 on 2019-11-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20191027_1810'),
        ('tournament', '0065_tournament_aypt_limited_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='scrub_attendee_property',
            field=models.ManyToManyField(to='registration.AttendeePropertyValue'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='scrub_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
