# Generated by Django 2.2.6 on 2019-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20191027_1810'),
        ('tournament', '0066_auto_20191117_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='scrub_application_question',
            field=models.ManyToManyField(to='registration.ApplicationQuestionValue'),
        ),
    ]
