# Generated by Django 2.2.9 on 2020-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0067_tournament_scrub_application_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='allow_oauth',
            field=models.BooleanField(default=False),
        ),
    ]
