# Generated by Django 3.1.6 on 2021-03-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0070_auto_20210219_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='jurors_enter_grades',
            field=models.BooleanField(default=False),
        ),
    ]
