# Generated by Django 3.1.6 on 2021-03-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0071_tournament_jurors_enter_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fa_show_grades',
            field=models.BooleanField(default=False),
        ),
    ]
