# Generated by Django 3.1.6 on 2021-03-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0074_auto_20210311_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fight_room_guest_policy',
            field=models.CharField(blank=True, choices=[('ALWAYS_ACCEPT', 'allow guests'), ('ALWAYS_DENY', 'deny guests'), ('ASK_MODERATOR', 'ask moderator to allow guests')], max_length=20, null=True),
        ),
    ]
