# Generated by Django 3.1.6 on 2021-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0075_tournament_fight_room_guest_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='room_show_grades',
            field=models.BooleanField(default=False),
        ),
    ]
