# Generated by Django 3.1.6 on 2021-04-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0076_tournament_room_show_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='fight_room_public_role',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('attendee', 'Participant'), ('moderator', 'Moderator')], max_length=20, null=True),
        ),
    ]
