# Generated by Django 3.1 on 2021-04-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0078_tournament_results_help_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='public_clock',
            field=models.BooleanField(default=False),
        ),
    ]
