# Generated by Django 3.2.1 on 2021-05-05 10:52

import apps.tournament.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0079_tournament_public_clock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='flag_pdf',
            field=models.FileField(blank=True, null=True, upload_to=apps.tournament.models.tournament_flag_directory),
        ),
    ]
