# Generated by Django 3.2.1 on 2021-06-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0080_alter_origin_flag_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='publish_participation',
            field=models.BooleanField(default=False),
        ),
    ]
