# Generated by Django 3.2.1 on 2021-06-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0081_origin_publish_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
