# Generated by Django 3.2.1 on 2021-07-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0082_origin_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='jury_chair_maximum_meet_origin',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
