# Generated by Django 4.2.1 on 2023-08-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0083_tournament_jury_chair_maximum_meet_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='oypt_multiple_oppositions',
            field=models.BooleanField(default=False),
        ),
    ]
