# Generated by Django 4.2.1 on 2023-08-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0084_tournament_oypt_multiple_oppositions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='publish_partial_grades',
            field=models.BooleanField(default=False),
        ),
    ]
