# Generated by Django 5.0.6 on 2024-07-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0085_tournament_publish_partial_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="feedback_locked_by_assistants",
            field=models.BooleanField(default=True),
        ),
    ]
