# Generated by Django 5.0.6 on 2024-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0086_tournament_feedback_locked_by_assistants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="slides_public",
            field=models.BooleanField(default=False),
        ),
    ]
