# Generated by Django 5.2.3 on 2025-11-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0087_tournament_slides_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="per_team_fee",
            field=models.BooleanField(default=False),
        ),
    ]
