# Generated by Django 5.2.3 on 2025-11-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0088_tournament_per_team_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="origin",
            name="team_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
