# Generated by Django 5.2.3 on 2025-11-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0089_origin_team_fee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="per_team_fee",
        ),
    ]
