# Generated by Django 5.2.15 on 2026-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0090_remove_tournament_per_team_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ranking_unrounded_tsp',
            field=models.BooleanField(default=False, help_text='Compute the total sum of points from the unrounded fight sums and round once for display (official IYPT behaviour since 2026). If unset, the total is the sum of the rounded fight SPs (legacy behaviour).', verbose_name='Ranking total from unrounded fight sums'),
        ),
    ]
