# Generated by Django 5.2.15 on 2026-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0090_remove_tournament_per_team_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ranking_unrounded_tsp',
            field=models.BooleanField(default=False, help_text='Round fight SPs half to even and compute the total sum of points from the unrounded fight sums, rounded once for display (matches the official IYPT arithmetic). If unset, fight SPs are rounded half up and the total is their sum (legacy behaviour).', verbose_name='Exact ranking arithmetic (half-even rounding)'),
        ),
    ]
