# Generated by Django 5.2.15 on 2026-07-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0090_remove_tournament_per_team_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='ranking_unrounded_tsp',
            field=models.BooleanField(default=False, help_text='Keep fight SPs and the total sum of points in full precision and round only for display (halves up). If unset, fight SPs are rounded half up per fight and the total is their sum (legacy behaviour).', verbose_name='Full-precision ranking arithmetic'),
        ),
    ]
