# Generated by Django 2.1.2 on 2018-10-07 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0053_tournament_jury_opt_weight_bias'),
        ('team', '0018_auto_20180314_1814'),
        ('jury', '0030_auto_20180802_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChairFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChairFeedbackCriterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ChairFeedbackGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.ChairFeedbackCriterion')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.ChairFeedback')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackGrade'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='jurorsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jury.JurorSession'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='chairfeedbackgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.FeedbackGrade'),
        ),
        migrations.AddField(
            model_name='chairfeedback',
            name='grades',
            field=models.ManyToManyField(through='feedback.ChairFeedbackGrade', to='feedback.ChairFeedbackCriterion'),
        ),
        migrations.AddField(
            model_name='chairfeedback',
            name='jurorsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jury.JurorSession'),
        ),
        migrations.AddField(
            model_name='chairfeedback',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
