# Generated by Django 2.1.2 on 2018-10-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0053_tournament_jury_opt_weight_bias'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedbackgrade',
            unique_together={('tournament', 'value')},
        ),
    ]
