# Generated by Django 2.1.2 on 2018-11-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20181007_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'permissions': (('change_all_feedback', 'Can change any feedback'),)},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
