# Generated by Django 2.1.2 on 2018-11-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20181110_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
