# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0029_auto_20170907_2101'),
        ('team', '0008_auto_20170115_2141'),
        ('account', '0007_auto_20170313_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ActiveUser')),
                ('origin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.Origin')),
                ('participation_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ParticipationRole')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('team_role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamRole')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
        ),
    ]
