# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170909_2138'),
        ('registration', '0002_auto_20170909_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Attendee')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProperty')),
            ],
        ),
    ]
