# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_userproperty_userpropertyvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertyvalue',
            name='int_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
