# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_userpropertyvalue_int_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpropertyvalue',
            name='date_value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpropertyvalue',
            name='datetime_value',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpropertyvalue',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userpropertyvalue',
            name='string_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpropertyvalue',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
