# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20171111_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='')),
                ('text_value', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='datetime_value',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='image_value',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='int_value',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='string_value',
        ),
        migrations.RemoveField(
            model_name='attendeepropertyvalue',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='date_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='datetime_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='image_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='int_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='string_value',
        ),
        migrations.RemoveField(
            model_name='userpropertyvalue',
            name='text_value',
        ),
        migrations.AddField(
            model_name='attendeepropertyvalue',
            name='propertyvalue_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.PropertyValue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpropertyvalue',
            name='propertyvalue_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.PropertyValue'),
            preserve_default=False,
        ),
    ]
