# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-25 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20171125_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeproperty',
            name='type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender')], max_length=30),
        ),
    ]
