# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20180101_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendeepropertyvalue',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='userpropertyvalue',
            unique_together=set([]),
        ),
    ]
