# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-01 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20180101_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeproperty',
            name='optional',
            field=models.ManyToManyField(blank=True, related_name='optional_properties', to='account.ParticipationRole'),
        ),
        migrations.AlterField(
            model_name='attendeeproperty',
            name='required',
            field=models.ManyToManyField(blank=True, related_name='required_properties', to='account.ParticipationRole'),
        ),
    ]
