# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_auto_20180107_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeproperty',
            name='type',
            field=models.CharField(blank=True, choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender'), ('preferred_name', 'preferred name'), ('preferred_name_short', 'preferred name short')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender'), ('preferred_name', 'preferred name'), ('preferred_name_short', 'preferred name short')], max_length=30),
        ),
    ]
