# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20180110_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Property')),
            ],
        ),
    ]
