# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_propertychoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='choices_value',
            field=models.ManyToManyField(blank=True, null=True, to='registration.PropertyChoice'),
        ),
    ]
