# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_propertyvalue_choices_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='choices_value',
            field=models.ManyToManyField(blank=True, to='registration.PropertyChoice'),
        ),
    ]
