# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20180111_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='bool_value',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender'), ('boolean', 'boolean'), ('preferred_name', 'preferred name'), ('preferred_name_short', 'preferred name short'), ('choice', 'Select One'), ('multiple_choice', 'Select Multiple')], max_length=30),
        ),
    ]
