# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_auto_20180115_0853'),
        ('registration', '0019_auto_20180111_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='conflict_origins',
            field=models.ManyToManyField(blank=True, to='tournament.Origin'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender'), ('boolean', 'boolean'), ('preferred_name', 'preferred name'), ('preferred_name_short', 'preferred name short'), ('choice', 'Select One'), ('multiple_choice', 'Select Multiple'), ('conflict_origins', 'Conflict with Origins')], max_length=30),
        ),
    ]
