# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_attendeeproperty_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeproperty',
            name='data_utilisation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation why this data is acquired'),
        ),
    ]
