# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_attendeeproperty_data_utilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvalue',
            name='country_value',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('text', 'text'), ('gender', 'gender'), ('boolean', 'boolean'), ('preferred_name', 'preferred name'), ('preferred_name_short', 'preferred name short'), ('choice', 'Select One'), ('multiple_choice', 'Select Multiple'), ('conflict_origins', 'Conflict with Origins'), ('country', 'Country (ISO)')], max_length=30),
        ),
    ]
