# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_auto_20180129_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeproperty',
            name='required_if',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.AttendeeProperty'),
        ),
    ]
