# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_participationrole_fee'),
        ('registration', '0030_auto_20180214_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeproperty',
            name='apply_required',
            field=models.ManyToManyField(blank=True, related_name='apply_properties', to='account.ParticipationRole'),
        ),
    ]
