# Generated by Django 2.0.3 on 2018-03-28 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_auto_20180328_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendeeproperty',
            old_name='optional_tmp',
            new_name='optional',
        ),
        migrations.RenameField(
            model_name='attendeeproperty',
            old_name='required_tmp',
            new_name='required',
        ),
    ]
