# Generated by Django 2.0.3 on 2018-03-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_auto_20180328_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendeepropertyvalue',
            old_name='property',
            new_name='att_property',
        ),
    ]
