# Generated by Django 2.1.5 on 2019-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_auto_20180328_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
