# Generated by Django 2.1.5 on 2019-02-20 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_participationrole_attending'),
        ('registration', '0039_auto_20190218_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('int', 'Integer'), ('string', 'String'), ('datetime', 'datetime'), ('date', 'date'), ('image', 'image'), ('pdf', 'pdf'), ('text', 'text'), ('boolean', 'boolean'), ('boolean_true', 'required true boolean')], max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ParticipationRole')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('string_value', models.CharField(blank=True, max_length=255, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('bool_value', models.NullBooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ApplicationQuestion')),
            ],
        ),
    ]
