# Generated by Django 2.1.5 on 2019-02-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_applicationquestion_applicationquestionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationquestion',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
