# Generated by Django 2.1.5 on 2019-02-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_participationrole_attending'),
        ('registration', '0041_auto_20190220_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='handled_as',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('declined', 'declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Attendee'),
        ),
    ]
