# Generated by Django 2.1.5 on 2019-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0042_auto_20190221_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='handled_as',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('declined', 'declined'), ('withdraw', 'withdrawn')], max_length=20, null=True),
        ),
    ]
