# Generated by Django 2.2 on 2019-04-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_applicationquestion_required_if'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
