# Generated by Django 2.1.8 on 2019-04-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_applicationquestion_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeproperty',
            name='edit_multi',
            field=models.BooleanField(default=False),
        ),
    ]
