# Generated by Django 2.2.6 on 2019-11-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0047_auto_20191027_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyvalue',
            options={'ordering': ('creation',)},
        ),
    ]
