# Generated by Django 2.2.9 on 2020-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0048_auto_20191127_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationquestion',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
