# Generated by Django 3.1.6 on 2021-02-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0049_applicationquestion_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestionvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='bool_value',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
