# Generated by Django 3.2.1 on 2021-05-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210327_1042'),
        ('registration', '0050_auto_20210206_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeproperty',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.property'),
        ),
        migrations.AlterField(
            model_name='attendeepropertyvalue',
            name='propertyvalue_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.propertyvalue'),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.activeuser'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='property_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.property'),
        ),
        migrations.AlterField(
            model_name='userpropertyvalue',
            name='propertyvalue_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registration.propertyvalue'),
        ),
        migrations.AlterField(
            model_name='userpropertyvalue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.activeuser'),
        ),
    ]
