# Generated by Django 3.2.1 on 2021-05-05 10:52

import apps.registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0051_auto_20210505_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationquestionvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to=apps.registration.models.dir_aq_path),
        ),
        migrations.AlterField(
            model_name='applicationquestionvalue',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to=apps.registration.models.dir_aq_path),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='file_value',
            field=models.FileField(blank=True, null=True, upload_to=apps.registration.models.dir_property_path),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='image_value',
            field=models.ImageField(blank=True, null=True, upload_to=apps.registration.models.dir_property_path),
        ),
    ]
