# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 23:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='roles',
            field=models.ManyToManyField(to='account.ParticipationRole'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ActiveUser'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.Attendee'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='tournaments',
            field=models.ManyToManyField(blank=True, through='account.Attendee', to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='activeuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set([('user', 'tournament')]),
        ),
    ]
