# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20161008_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='roles',
            field=models.ManyToManyField(blank=True, to='account.ParticipationRole'),
        ),
    ]
