# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20161009_0118'),
        ('account', '0003_auto_20161009_0022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='user',
            new_name='active_user',
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set([('active_user', 'tournament')]),
        ),
    ]
