# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20161009_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='type',
            field=models.CharField(blank=True, choices=[('fa', 'Fight Assistant'), ('st', 'Student'), ('ju', 'Juror'), ('vi', 'Visitor'), ('ec', 'EC Member')], max_length=2, null=True),
        ),
    ]
