# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_participationrole_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'permissions': (('view_person', 'Can list all person details'), ('view_all_persons', 'Can list all persons'))},
        ),
    ]
