# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Attendee'),
        ),
    ]
