# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20170313_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationrole',
            name='type',
            field=models.CharField(blank=True, choices=[('fa', 'Fight Assistant'), ('st', 'Student'), ('tl', 'Team Leader'), ('ju', 'Juror'), ('vi', 'Visitor'), ('ec', 'EC Member')], max_length=2, null=True),
        ),
    ]
