# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('account', '0008_auto_20170909_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
