# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_attendee_ui_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='ui_skin',
            field=models.CharField(blank=True, choices=[('skin-blue', 'blue'), ('skin-blue-light', 'blue light'), ('skin-yellow', 'yellow'), ('skin-yellow-light', 'yellow light'), ('skin-green', 'green'), ('skin-green-light', 'green light'), ('skin-purple', 'purple'), ('skin-purple-light', 'purple light'), ('skin-red', 'red'), ('skin-red-light', 'red light'), ('skin-black', 'black'), ('skin-black-light', 'black light')], max_length=50, null=True),
        ),
    ]
