# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180124_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
