# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-21 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_participationrole_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='manager_approvable',
            field=models.BooleanField(default=False),
        ),
    ]
