# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_participationrole_manager_approvable'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='approvable_by',
            field=models.ManyToManyField(to='account.ParticipationRole'),
        ),
        migrations.AlterField(
            model_name='participationrole',
            name='type',
            field=models.CharField(blank=True, choices=[('fa', 'Fight Assistant'), ('st', 'Student'), ('tl', 'Team Leader'), ('ju', 'Juror'), ('vi', 'Visitor'), ('ec', 'EC Member'), ('tm', 'Team Manager'), ('lc', 'Local Organising Committee'), ('ic', 'International Organising Committee')], max_length=2, null=True),
        ),
    ]
