# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180225_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationrole',
            name='manager_approvable',
        ),
    ]
