# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-25 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_participationrole_manager_approvable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationrole',
            name='approvable_by',
            field=models.ManyToManyField(blank=True, to='account.ParticipationRole'),
        ),
    ]
