# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180225_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='global_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
