# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-13 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_participationrole_global_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='attending',
            field=models.BooleanField(default=True),
        ),
    ]
