# Generated by Django 2.1.5 on 2019-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_participationrole_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='require_possiblejuror',
            field=models.BooleanField(default=False),
        ),
    ]
