# Generated by Django 2.1.5 on 2019-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_participationrole_require_possiblejuror'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
