# Generated by Django 2.1.5 on 2019-03-16 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('tournament', '0060_tournament_possiblejuror_reapply'),
        ('account', '0022_participationrole_application_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiPermissionsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('apipermissionsmixin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.ApiPermissionsMixin')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.apipermissionsmixin',),
        ),
        migrations.AddField(
            model_name='apipermissionsmixin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='apiuser_set', related_query_name='apiuser', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='apipermissionsmixin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='apiuser_set', related_query_name='apiuser', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='account.ApiUser', verbose_name='User'),
        ),
    ]
