# Generated by Django 2.1.5 on 2019-04-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_apiuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
