# Generated by Django 3.1.6 on 2021-02-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20190407_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationrole',
            name='virtual_room_role',
            field=models.CharField(blank=True, choices=[('guest', 'Guest'), ('attendee', 'Participant'), ('moderator', 'Moderator')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participationrole',
            name='type',
            field=models.CharField(blank=True, choices=[('fa', 'Fight Assistant'), ('st', 'Student'), ('tl', 'Team Leader'), ('ju', 'Juror'), ('ch', 'Chair'), ('vi', 'Visitor'), ('ec', 'EC Member'), ('tm', 'Team Manager'), ('lc', 'Local Organising Committee'), ('ic', 'International Organising Committee')], max_length=2, null=True),
        ),
    ]
