# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('team', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Attendee'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamRole'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='team.TeamMember', to='account.Attendee'),
        ),
        migrations.AddField(
            model_name='team',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Country'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
    ]
