# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20161125_1204'),
        ('team', '0004_remove_team_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='origin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Origin'),
            preserve_default=False,
        ),
    ]
