# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrole',
            name='type',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('member', 'Member'), ('leader', 'Leader')], max_length=15, null=True),
        ),
    ]
