# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20161125_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['origin__name'], 'permissions': (('view_teams', 'Can list all team details'),)},
        ),
    ]
