# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170115_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
