# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-15 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_teamrole_participation_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['origin__name'], 'permissions': (('view_teams', 'Can list all team details'),)},
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='type',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('member', 'Member'), ('leader', 'Leader'), ('visitor', 'Visitor'), ('juror', 'Juror')], max_length=15, null=True),
        ),
    ]
