# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-16 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_participationrole_groups'),
        ('team', '0011_auto_20180115_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamrole',
            name='participation_role',
        ),
        migrations.AddField(
            model_name='teamrole',
            name='participation_roles',
            field=models.ManyToManyField(blank=True, to='account.ParticipationRole'),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='type',
            field=models.CharField(blank=True, choices=[('captain', 'Captain'), ('member', 'Member'), ('leader', 'Leader'), ('visitor', 'Visitor'), ('juror', 'Juror'), ('leaderjuror', 'Teamleader Juror')], max_length=15, null=True),
        ),
    ]
