# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-17 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20180116_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notify_applications',
            field=models.BooleanField(default=True),
        ),
    ]
