# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_team_notify_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrole',
            name='members_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamrole',
            name='members_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
