# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20180121_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_competing',
            field=models.BooleanField(default=True),
        ),
    ]
