# Generated by Django 2.2.6 on 2019-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0065_tournament_aypt_limited_problems'),
        ('team', '0018_auto_20180314_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='aypt_prepared_problems',
            field=models.ManyToManyField(to='tournament.Problem'),
        ),
    ]
