# Generated by Django 3.2.1 on 2021-06-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0019_team_aypt_prepared_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='publish_participation',
            field=models.BooleanField(default=False),
        ),
    ]
