# Generated by Django 3.2.1 on 2021-06-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0020_team_publish_participation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='publish_participation',
        ),
    ]
