# Generated by Django 3.2.1 on 2021-06-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0021_remove_team_publish_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='storage_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
