# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failure', 'failure')], default='processing', max_length=25)),
            ],
        ),
    ]
