# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20170112_1506'),
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
