# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_pdf_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failure', 'failure'), ('upload', 'uploaded')], default='processing', max_length=25),
        ),
    ]
