# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20170112_1506'),
        ('printer', '0005_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdf',
            unique_together=set([('tournament', 'name')]),
        ),
    ]
