# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0006_auto_20170123_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('type', models.CharField(blank=True, choices=[('preview', 'Preview'), ('ranking', 'Ranking'), ('results', 'Results')], max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pdf',
            name='tags',
            field=models.ManyToManyField(blank=True, to='printer.PdfTag'),
        ),
    ]
