# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20170112_1506'),
        ('printer', '0007_auto_20170209_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftag',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
