# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170115_2141'),
        ('printer', '0008_pdftag_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('src', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ActiveUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='template',
            name='src',
        ),
        migrations.AddField(
            model_name='templateversion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.Template'),
        ),
    ]
