# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 10:01
from __future__ import unicode_literals

import apps.printer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0010_auto_20170302_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='expire_at',
            field=models.DateTimeField(default=apps.printer.models.get_expire_datetime),
        ),
        migrations.AddField(
            model_name='pdf',
            name='rendered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
