# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0011_auto_20170309_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateversion',
            name='src',
            field=models.TextField(blank=True),
        ),
    ]
