# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_tournament_default_result_template'),
        ('printer', '0012_auto_20170311_1346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pdftag',
            unique_together=set([('tournament', 'type')]),
        ),
    ]
