# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0016_auto_20170628_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['-rendered_at']},
        ),
        migrations.AlterField(
            model_name='pdf',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failure', 'failure'), ('error', 'error'), ('upload', 'uploaded')], default='processing', max_length=25),
        ),
    ]
