# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-08 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_tournament_default_round_problemselect'),
        ('printer', '0019_auto_20170707_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('preview', 'Preview'), ('ranking', 'Ranking'), ('results', 'Results'), ('jury_round', 'Jury Round Plan'), ('team_round', 'Team Round Plan'), ('jury_feedback', 'Jury Fight Feedback'), ('problem_select', 'Problem Selection for last PF')], max_length=25)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printer.Template')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_template', to='tournament.Tournament')),
            ],
        ),
    ]
