# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_auto_20180109_1250'),
        ('printer', '0020_defaulttemplate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='defaulttemplate',
            unique_together=set([('tournament', 'type')]),
        ),
    ]
