# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0023_auto_20180316_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='files',
            field=models.ManyToManyField(blank=True, to='printer.Pdf'),
        ),
    ]
