# Generated by Django 2.2 on 2019-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0026_auto_20190408_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='status',
            field=models.CharField(choices=[('processing', 'processing'), ('success', 'success'), ('failure', 'failure'), ('error', 'error'), ('upload', 'uploaded'), ('merge', 'merged')], default='processing', max_length=25),
        ),
    ]
