# Generated by Django 4.2.1 on 2023-07-17 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0083_tournament_jury_chair_maximum_meet_origin'),
        ('printer', '0029_alter_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('hostname', models.CharField(max_length=256, verbose_name='hostname')),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=64, verbose_name='username')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
