# Generated by Django 5.2.1 on 2025-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0027_auto_20210327_1042"),
        ("printer", "0032_alter_defaulttemplate_type_alter_pdftag_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdf",
            name="inbox_attendees",
            field=models.ManyToManyField(blank=True, to="account.attendee"),
        ),
    ]
