# Generated by Django 5.2.3 on 2025-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printer", "0033_pdf_inbox_attendees"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileserver",
            name="path",
            field=models.CharField(default=".", max_length=256, verbose_name="path"),
        ),
    ]
