#!/usr/bin/env python
# -*- coding: utf-8 -*-


ASSETS = {
    "jquery_js": "AdminLTE/bower_components/jquery/dist/jquery.min.js",
    "jquery_ui_js": "AdminLTE/plugins/jQueryUI/jquery-ui.min.js",
    "bootstrap_css": "AdminLTE/bower_components/bootstrap/dist/css/bootstrap.min.css",
    "bootstrap_js": "AdminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js",
    "moment_js": "AdminLTE/bower_components/moment/moment.js",
    "fastclick_js": "AdminLTE/bower_components/fastclick/lib/fastclick.js",
    "fontawesome_css": "Font-Awesome/css/font-awesome.min.css",
    "ionicons_css": "ionicons/css/ionicons.min.css",
    #'raphael_js': 'https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js',
    #'html5shiv_js': 'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js',
    #'respond_js': 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js',
    # ----------
    # Charts
    "chartjs_js": "js/Chart.min.js",
    "flot_js": "AdminLTE/plugins/flot/jquery.flot.min.js",
    "morrisjs_css": "AdminLTE/plugins/morris/morris.css",
    "morrisjs_js": "AdminLTE/plugins/morris/morris.min.js",
    "sparkline_js": "AdminLTE/plugins/sparkline/jquery.sparkline.min.js",
    # ----------
    # Form Elements
    "bootstrap_slider_css": "AdminLTE/plugins/bootstrap-slider/slider.css",
    "bootstrap_slider_js": "AdminLTE/plugins/bootstrap-slider/bootstrap-slider.js",
    "ionslider_css": "AdminLTE/plugins/ionslider/ion.rangeSlider.css",
    "ionslider_skin_flat_css": "AdminLTE/plugins/ionslider/ion.rangeSlider.skinFlat.css",
    "ionslider_skin_nice_css": "AdminLTE/plugins/ionslider/ion.rangeSlider.skinNice.css",
    "ionslider_js": "AdminLTE/plugins/ionslider/ion.rangeSlider.min.js",
    "bootstrap_datepicker_css": "AdminLTE/plugins/datepicker3.css",
    "bootstrap_datepicker_js": "AdminLTE/plugins/bootstrap-datepicker.js",
    "bootstrap_daterangepicker_css": "AdminLTE/plugins/daterangepicker/daterangepicker-bs3.css",
    "bootstrap_daterangepicker_js": "AdminLTE/plugins/daterangepicker/daterangepicker.js",
    "bootstrap_colorpicker_css": "AdminLTE/plugins/colorpicker/bootstrap-colorpicker.min.css",
    "bootstrap_colorpicker_js": "AdminLTE/plugins/colorpicker/bootstrap-colorpicker.min.js",
    "bootstrap_timepicker_css": "AdminLTE/plugins/timepicker/bootstrap-timepicker.min.css",
    "bootstrap_timepicker_js": "AdminLTE/plugins/timepicker/bootstrap-timepicker.min.js",
    "icheck_css": "AdminLTE/plugins/iCheck/all.css",
    "icheck_js": "AdminLTE/plugins/iCheck/icheck.min.js",
    "input_mask_js": "AdminLTE/plugins/input-mask/jquery.inputmask.js",
    "input_mask_extensions_js": "AdminLTE/plugins/input-mask/jquery.inputmask.extensions.js",
    "input_mask_date_ext_js": "AdminLTE/plugins/input-mask/jquery.inputmask.date.extensions.js",
    "input_mask_numeric_ext_js": "AdminLTE/plugins/input-mask/jquery.inputmask.numeric.extensions.js",
    "input_mask_phone_ext_js": "AdminLTE/plugins/input-mask/jquery.inputmask.phone.extensions.js",
    "input_mask_regex_ext_js": "AdminLTE/plugins/input-mask/jquery.inputmask.regex.extensions.js",
    "select2_css": "AdminLTE/plugins/select2/select2.min.css",
    "select2_js": "AdminLTE/plugins/select2/select2.full.min.js",
    # ----------
    # Editors
    "bootstrap_wysihtml5_css": "AdminLTE/plugins/bootstrap3-wysihtml5.all.min.css",
    "bootstrap_wysihtml5_js": "AdminLTE/plugins/bootstrap3-wysihtml5.all.min.js",
    "ckeditor_js": "AdminLTE/plugins/ckeditor/ckeditor.js",
    # ----------
    # Other
    "datatables_css": "AdminLTE/plugins/datatables/jquery.dataTables.min.css",
    "datatables_js": "AdminLTE/plugins/datatables/jquery.dataTables.min.js",
    "datatables_bootstrap_css": "AdminLTE/plugins/datatables/dataTables.bootstrap.css",
    "datatables_bootstrap_js": "AdminLTE/plugins/datatables/dataTables.bootstrap.js",
    "fullcalendar_css": "AdminLTE/plugins/fullcalendar/fullcalendar.min.css",
    "fullcalendar_print_css": "AdminLTE/plugins/fullcalendar/fullcalendar.print.css",
    "fullcalendar_js": "AdminLTE/plugins/fullcalendar/fullcalendar.min.js",
    "knob_js": "AdminLTE/plugins/knob/jquery.knob.js",
    "jvectormap_css": "AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.css",
    "jvectormap_js": "AdminLTE/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js",
    "slimscroll_js": "AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js",
    "pace_css": "AdminLTE/plugins/pace/pace.min.css",
    "pace_js": "AdminLTE/plugins/pace/pace.min.js",
    # ----------
}
