from django import forms
from django.urls import path, re_path

from .preview import (
    ApplyPossibleJurorPreview,
    ApplyTeamManager,
    ApplyTeamMember,
    ApplyWithRoleWizard,
    AttendeePreview,
    PayFeePreview,
    TeamOverviewPreview,
)
from .views import (
    ApplicationFileView,
    ApplicationsList,
    AssociateToTeam,
    DataDownload,
    DataOverview,
    EditAttendeeData,
    EditTeamMemberData,
    FilePropertyView,
    ListManageableTeams,
    RoleApplicationQuestionDownload,
    RoleApplicationsAccept,
    RoleApplicationsDecline,
    RoleApplicationsList,
    TeamApplicationsAccept,
    TeamApplicationsDecline,
    TeamApplicationsList,
    TeamMemberAccept,
    TeamMemberDecline,
    TeamMemberDelete,
    TeamMemberEdit,
    TournamentLogo,
    WithdrawApplication,
    WithdrawPossible,
)

app_name = "registration"

urlpatterns = [
    #    url(r'^overview/$', Overview.as_view() ,name="overview" ),
    path("list/", ApplicationsList.as_view(), name="applications"),
    path(
        "withdraw/application/<int:id>/",
        WithdrawApplication.as_view(),
        name="withdraw_application",
    ),
    path(
        "withdraw/possible/<int:id>/",
        WithdrawPossible.as_view(),
        name="withdraw_possible",
    ),
    path(
        "accept/team/list",
        TeamApplicationsList.as_view(),
        name="list_team_applications",
    ),
    path(
        "accept/team/<int:id>/",
        TeamApplicationsAccept.as_view(),
        name="accept_team_application",
    ),
    path(
        "accept/team/<int:id>/decline/",
        TeamApplicationsDecline.as_view(),
        name="decline_team_application",
    ),
    path(
        "accept/role/list/",
        RoleApplicationsList.as_view(),
        name="list_role_applications",
    ),
    path(
        "accept/role/<int:id>/",
        RoleApplicationsAccept.as_view(),
        name="accept_role_application",
    ),
    path(
        "accept/role/download/<int:role_id>/",
        RoleApplicationQuestionDownload.as_view(),
        name="download_role_application_question",
    ),
    path(
        "accept/role/<int:id>/decline/",
        RoleApplicationsDecline.as_view(),
        name="decline_role_application",
    ),
    path("overview/", AttendeePreview(forms.Form), name="overview"),
    path(
        "overview/edit/<int:id>/",
        EditAttendeeData.as_view(),
        name="change_attendeeproperty",
    ),
    path("overview/export/", DataDownload.as_view(), name="download_attendeeproperty"),
    path("manage/list/", ListManageableTeams.as_view(), name="manageable_teams"),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/accept/(?P<id>[0-9]+)/$",
        TeamMemberAccept.as_view(),
        name="team_member_accept",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/decline/(?P<id>[0-9]+)/$",
        TeamMemberDecline.as_view(),
        name="team_member_decline",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/edit/(?P<id>[0-9]+)/$",
        TeamMemberEdit.as_view(),
        name="team_member_edit",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/data/(?P<id>[0-9]+)/$",
        EditTeamMemberData.as_view(),
        name="team_member_data",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/delete/(?P<id>[0-9]+)/$",
        TeamMemberDelete.as_view(),
        name="team_member_delete",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/invoice/$",
        PayFeePreview(forms.Form),
        name="team_payment",
    ),
    re_path(
        r"^manage/team/(?P<s_team>[-\w]+)/$",
        TeamOverviewPreview(forms.Form),
        name="team_overview",
    ),
    path("data/", DataOverview.as_view(), name="attendeeproperty"),
    re_path(
        r"^data/file/(?P<typ>[au])/(?P<user>[0-9]+)/(?P<id>[0-9]+)/(?P<name>.*)$",
        FilePropertyView.as_view(),
        name="file_property",
    ),
    re_path(
        r"^application/file/(?P<id>[0-9]+)/(?P<name>.*).pdf$",
        ApplicationFileView.as_view(),
        name="application_file",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/role/$",
        ApplyWithRoleWizard.as_view(),
        name="apply_participationrole",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/role/(?P<role>[0-9]*)/$",
        ApplyWithRoleWizard.as_view(),
        name="apply_preselected_participationrole",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/team/$", ApplyTeamManager(forms.Form), name="apply_team"
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/member/$",
        ApplyTeamMember(forms.Form),
        name="apply_teammember",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/member/(?P<role>[0-9]+)/$",
        ApplyTeamMember(forms.Form),
        name="apply_preselected_teammember",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/member/(?P<visitor>[visitor]+)/$",
        ApplyTeamMember(forms.Form),
        name="apply_visitor_teammember",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/associate/$",
        AssociateToTeam.as_view(),
        name="associate_to_team",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/jurors/apply$",
        ApplyPossibleJurorPreview(forms.Form),
        name="apply_possiblejuror",
    ),
    re_path(
        r"^(?P<t_slug>[-\w]+)/logo/$", TournamentLogo.as_view(), name="tournament_logo"
    ),
]
