# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-08 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('plan', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplaceholder',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='stageattendanceplaceholder',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.FightRole'),
        ),
        migrations.AddField(
            model_name='stageattendanceplaceholder',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Stage'),
        ),
        migrations.AddField(
            model_name='stageattendanceplaceholder',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.TeamPlaceholder'),
        ),
        migrations.AddField(
            model_name='stageattendance',
            name='active_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamMember'),
        ),
        migrations.AddField(
            model_name='stageattendance',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.FightRole'),
        ),
        migrations.AddField(
            model_name='stageattendance',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Stage'),
        ),
        migrations.AddField(
            model_name='stageattendance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.AddField(
            model_name='stage',
            name='attendee_placeholders',
            field=models.ManyToManyField(through='plan.StageAttendancePlaceholder', to='plan.TeamPlaceholder'),
        ),
        migrations.AddField(
            model_name='stage',
            name='attendees',
            field=models.ManyToManyField(through='plan.StageAttendance', to='team.Team'),
        ),
        migrations.AddField(
            model_name='stage',
            name='fight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Fight'),
        ),
        migrations.AddField(
            model_name='stage',
            name='presented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presented_in', to='tournament.Problem'),
        ),
        migrations.AddField(
            model_name='stage',
            name='rejections',
            field=models.ManyToManyField(to='tournament.Problem'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='room',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
        ),
        migrations.AddField(
            model_name='fight',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Room'),
        ),
        migrations.AddField(
            model_name='fight',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.Round'),
        ),
    ]
