# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20161009_0118'),
        ('plan', '0002_auto_20161008_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='fightrole',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
