# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_fightrole_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'ordering': ['order']},
        ),
    ]
