# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20161009_1842'),
        ('plan', '0005_room_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Attendee'),
        ),
    ]
