# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20161105_1907'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='round',
            managers=[
                ('selectives', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='type',
            field=models.CharField(choices=[('s', 'selective PF'), ('f', 'final PF')], default='s', max_length=1),
        ),
    ]
