# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20161105_1933'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='round',
            managers=[
            ],
        ),
    ]
