# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_remove_tournament_final_fight'),
        ('plan', '0010_fightrole_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('order', 'tournament')]),
        ),
    ]
