# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_auto_20161125_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='rejections',
            field=models.ManyToManyField(blank=True, to='tournament.Problem'),
        ),
        migrations.AlterField(
            model_name='stageattendance',
            name='active_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.TeamMember'),
        ),
    ]
