# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_auto_20161125_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageattendanceplaceholder',
            name='role',
        ),
        migrations.RemoveField(
            model_name='stageattendanceplaceholder',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='stageattendanceplaceholder',
            name='team',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='attendee_placeholders',
        ),
        migrations.AddField(
            model_name='stageattendance',
            name='team_placeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.TeamPlaceholder'),
        ),
        migrations.AlterField(
            model_name='stageattendance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
        migrations.DeleteModel(
            name='StageAttendancePlaceholder',
        ),
    ]
