# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_auto_20161213_1247'),
        ('plan', '0014_auto_20161213_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplaceholder',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
