# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0015_teamplaceholder_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplaceholder',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
        ),
    ]
