# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0016_auto_20161219_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='presented',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_in', to='tournament.Problem'),
        ),
    ]
