# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0018_auto_20161219_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='publish_grades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fight',
            name='publish_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='publish_ranking',
            field=models.BooleanField(default=False),
        ),
    ]
