# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0019_auto_20170106_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fight',
            options={'ordering': ['room__name'], 'permissions': (('view_fight_operator', 'Can list fight operators/locks'), ('change_fight_operator', 'Can change fight operators/locks'), ('publish_fights', 'Can publish fights'), ('delete_final', 'Delete Final'), ('change_final', 'Change Final'))},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['order'], 'permissions': (('apply_schedule', 'Apply a schedule to real teams'), ('import_curiie', 'Import Curiie Data'), ('view_plan', 'View plan'))},
        ),
        migrations.AlterModelOptions(
            name='teamplaceholder',
            options={'permissions': (('assign_placeholders', 'Assign Teams to placeholders'), ('view_placeholders', 'View Teamplaceholders'))},
        ),
    ]
