# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0011_auto_20170309_1001'),
        ('plan', '0020_auto_20170115_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='pdf_preview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.Pdf'),
        ),
    ]
