# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0014_auto_20170423_1354'),
        ('plan', '0023_fight_pdf_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='pdf_juryplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.Pdf'),
        ),
    ]
