# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0016_auto_20170628_2034'),
        ('plan', '0024_round_pdf_juryplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='pdf_teamplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_round', to='printer.Pdf'),
        ),
        migrations.AlterField(
            model_name='round',
            name='pdf_juryplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_round', to='printer.Pdf'),
        ),
    ]
