# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0018_auto_20170705_1708'),
        ('plan', '0026_round_pdf_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='pdf_jury_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jury_feedback', to='printer.Pdf'),
        ),
    ]
