# Generated by Django 2.0.3 on 2018-06-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0029_auto_20170707_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='publish_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
