# Generated by Django 2.0.3 on 2018-07-13 11:50

from django.db import migrations

def forward(apps, schema_editor):
    Fight = apps.get_model("plan", "Fight")
    for fight in Fight.objects.all():
        if fight.operator:
            fight.operators.add(fight.operator)

class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0031_auto_20180713_1150'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
