# Generated by Django 2.0.3 on 2018-07-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0032_auto_20180713_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='operator',
        ),
    ]
