# Generated by Django 2.2 on 2019-04-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0026_auto_20190408_1053'),
        ('plan', '0033_remove_fight_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='pdf_grading_sheets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='printer.Pdf'),
        ),
    ]
