# Generated by Django 2.1.8 on 2019-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0034_stage_pdf_grading_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='preview_fixed_problem',
            field=models.BooleanField(default=False),
        ),
    ]
