# Generated by Django 2.1.8 on 2019-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0035_round_preview_fixed_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='publish_jurors',
            field=models.BooleanField(default=False),
        ),
    ]
