# Generated by Django 3.1.6 on 2021-02-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual', '0001_initial'),
        ('plan', '0039_round_grading_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='virtual_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtual.bbbinstance'),
        ),
    ]
