# Generated by Django 3.1.6 on 2021-04-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0041_stage_jurors_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='currently_active',
            field=models.BooleanField(default=False),
        ),
    ]
