# Generated by Django 3.2.1 on 2021-06-19 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0082_origin_timezone'),
        ('plan', '0043_auto_20210619_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('selective', 'selective PF'), ('final', 'final PF'), ('opening', 'opening ceremony'), ('closing', 'closing ceremony')], max_length=30, null=True)),
                ('round', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
            options={
                'ordering': ['time_start'],
                'unique_together': {('name', 'tournament')},
            },
        ),
        migrations.DeleteModel(
            name='RoundPlaceholder',
        ),
    ]
