# Generated by Django 3.2.1 on 2021-06-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0045_event_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='review_phase',
            field=models.BooleanField(default=True),
        ),
    ]
