# Generated by Django 3.2.1 on 2021-07-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20210327_1042'),
        ('plan', '0046_round_review_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='virtual_attendees',
            field=models.ManyToManyField(blank=True, related_name='virtual_rooms', to='account.Attendee'),
        ),
    ]
