# Generated by Django 3.2.14 on 2022-07-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0049_round_reserved_jurors'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='virtual_record',
            field=models.BooleanField(default=False),
        ),
    ]
