# Generated by Django 5.0.3 on 2024-03-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0050_fight_virtual_record'),
        ('printer', '0031_fileserver_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='pdf_grade_overview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_overview', to='printer.pdf'),
        ),
    ]
