# Generated by Django 5.0.6 on 2024-07-09 13:38

import apps.plan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0051_fight_pdf_grade_overview"),
    ]

    operations = [
        migrations.AddField(
            model_name="stage",
            name="pdf_presentation",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.plan.models.dir_presentation_path
            ),
        ),
    ]
