# Generated by Django 5.0.6 on 2024-07-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0052_stage_pdf_presentation"),
    ]

    operations = [
        migrations.AddField(
            model_name="fight",
            name="publish_slides",
            field=models.BooleanField(default=False),
        ),
    ]
