# Generated by Django 5.0.6 on 2024-07-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0053_fight_publish_slides"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="feedback_locked",
            field=models.BooleanField(default=False),
        ),
    ]
