# Generated by Django 5.2.3 on 2025-07-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0054_round_feedback_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageattendance",
            name="voided",
            field=models.BooleanField(default=False),
        ),
    ]
