# Generated by Django 5.2.3 on 2025-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0055_stageattendance_voided"),
    ]

    operations = [
        migrations.AddField(
            model_name="stageattendance",
            name="penalty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
