# Generated by Django 5.2.3 on 2025-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan", "0056_stageattendance_penalty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stageattendance",
            name="penalty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
