# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
