# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-14 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180214_1438'),
        ('bank', '0003_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='aborted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aboarted_payments', to='account.Attendee'),
        ),
    ]
