# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0043_tournament_fee_team'),
        ('bank', '0005_propertyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfee',
            name='tournament',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tournament.Tournament'),
            preserve_default=False,
        ),
    ]
