# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_propertyfee_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfee',
            name='if_not_true',
            field=models.ManyToManyField(blank=True, related_name='not_true_propertyfee', to='registration.AttendeeProperty'),
        ),
        migrations.AlterField(
            model_name='propertyfee',
            name='if_true',
            field=models.ManyToManyField(blank=True, related_name='true_propertyfee', to='registration.AttendeeProperty'),
        ),
    ]
