# Generated by Django 2.0.3 on 2018-04-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_participationrole_attending'),
        ('bank', '0009_auto_20180430_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ref_attendee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_attendee', to='account.Attendee'),
        ),
    ]
