# Generated by Django 2.0.3 on 2018-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20180504_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='abort_reason',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
